name: dezmente
description: "app de deteccao de deficit cognitivo"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^3.1.0
  google_sign_in: ^5.2.1
  provider: ^6.0.1
  confirm_dialog: ^1.0.0
  widget_arrows: ^0.2.0-nullsafety.0
  flutter_chat_bubble: ^2.0.0
  circular_widgets: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cube/
    - assets/images/animals/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
