name: dezmente
description: "App de Deteccao de Deficit Cognitivo"

publish_to: "none"

version: 0.9.6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audioplayers: ^5.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  google_sign_in: ^6.1.4
  provider: ^6.0.1
  confirm_dialog: ^1.0.0
  widget_arrows: ^0.5.2
  flutter_chat_bubble: ^2.0.0
  circular_widgets: ^3.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cube/
    - assets/images/cube_new/
    - assets/images/animals/
    - assets/images/slices/
    - assets/images/slices_new/
    - assets/images/similarity/
    - assets/audio/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
    - family: PassionOne
      fonts:
        - asset: assets/fonts/passion_one/PassionOne-Regular.ttf
        - asset: assets/fonts/passion_one/PassionOne-Bold.ttf
        - asset: assets/fonts/passion_one/PassionOne-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/dezment_ico.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

